services:

  APPNAME_fe-node:
    build:
      dockerfile: ./docker/node/Dockerfile.node
    container_name: APPNAME_fe-node
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
      - "24678:24678"
    networks:
      - APPNAME_-network
    restart: always

  APPNAME_api:
    build: 
      dockerfile: ./docker/php/Dockerfile.php
    container_name: APPNAME_
    working_dir: /var/www/APPNAME_api
    networks:
      - APPNAME_-network
    ports:
      - "9000:9000"

  APPNAME_-webserver:
    image: nginx:alpine
    container_name: webserver
    volumes:
      - ./backend:/var/www/APPNAME_api
      - ./docker/nginx/api.conf:/etc/nginx/conf.d/api.conf
      - ./frontend:/app
      - ./docker/nginx/node.conf:/etc/nginx/conf.d/node.conf
    ports:
      - "80:80"
      - "443:443"
    links:
      - APPNAME_api
    networks:
      - APPNAME_-network

  db:
    image: postgres:15
    container_name: APPNAME__db
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - APPNAME_-network

  APPNAME_-minio:
    image: minio/minio
    container_name: APPNAME_-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_DEFAULT_BUCKETS: APPNAME_bucket
    volumes:
      - miniostorage:/data
    ports:
      - "9001:9000"
      - "9002:9001"
    networks:
      - APPNAME_-network
    restart: always

volumes:
  miniostorage:
    driver: local
  db_data:
    driver: local

networks:
  APPNAME_-network:
    driver: bridge


