services:

  # database:
  #   image: mysql:8.0
  #   container_name: irist_db
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "3308:3306"
  #   environment:
  #     MYSQL_DATABASE: bts_laravel
  #     MYSQL_ROOT_PASSWORD: password
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   networks:
  #     - app-network
  #   volumes:
  #     - irist_data:/var/lib/mysql/
  #     - .docker/mysql/mysql.cnf:/etc/mysql/mysql.cnf


  app:
    build: 
      context: .
      dockerfile: ./docker/php/Dockerfile.php
    volumes:
      - .:/var/www/
    container_name: app
    working_dir: /var/www
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
      # - "443:443"
    links:
      - app
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge

volumes:
  data:
    driver: local 