services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: homestead
      MYSQL_PASSWORD: homestead
    ports:
      - "3306:3306"
    networks:
      - internal
    volumes:
      - data:/var/lib/mysql

  webserver:
    image: nginx:alpine
    container_name: webserver
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
      # - "443:443"
    links:
      - app
    networks:
      - internal

  app:
    build: 
      context: .
      dockerfile: ./docker/php/Dockerfile.php
    volumes:
      - .:/var/www/
    container_name: app
    working_dir: /var/www
    links:
      - mysql
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  data:
    driver: local